# Dockerfile
FROM node:18.7.0 AS build

WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "yarn.lock", "./"]
RUN yarn
COPY . .

ARG CANVAS_BLOCKS_BASE_DOMAINS
ENV CANVAS_BLOCKS_BASE_DOMAINS=$CANVAS_BLOCKS_BASE_DOMAINS

ARG CANVAS_BLOCKS_THEME_HOST
ENV CANVAS_BLOCKS_THEME_HOST=$CANVAS_BLOCKS_THEME_HOST

ARG CANVAS_BLOCKS_THEME_CONTACT_NAME
ENV CANVAS_BLOCKS_THEME_CONTACT_NAME=$CANVAS_BLOCKS_THEME_CONTACT_NAME

ARG CANVAS_BLOCKS_THEME_CONTACT_EMAIL
ENV CANVAS_BLOCKS_THEME_CONTACT_EMAIL=$CANVAS_BLOCKS_THEME_CONTACT_EMAIL

RUN yarn build-theme

FROM joseluisq/static-web-server:latest as prod
COPY --from=build /usr/src/app/dist /public
COPY ./static-web-server.toml /config.toml
ENV SERVER_CONFIG_FILE=/config.toml
EXPOSE 80