# Dockerfile
FROM node:20.10.0 AS build

WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "yarn.lock", "./"]
RUN yarn
RUN apt-get update || : && apt-get install python3 python3-pip -y
RUN pip3 install picosvg
COPY . .

ARG CANVAS_BLOCKS_BASE_DOMAINS
ENV CANVAS_BLOCKS_BASE_DOMAINS=$CANVAS_BLOCKS_BASE_DOMAINS

ARG CANVAS_BLOCKS_THEME_HOST
ENV CANVAS_BLOCKS_THEME_HOST=$CANVAS_BLOCKS_THEME_HOST

ARG CANVAS_BLOCKS_THEME_CONTACT_NAME
ENV CANVAS_BLOCKS_THEME_CONTACT_NAME=$CANVAS_BLOCKS_THEME_CONTACT_NAME

ARG CANVAS_BLOCKS_THEME_CONTACT_LINK
ENV CANVAS_BLOCKS_THEME_CONTACT_LINK=$CANVAS_BLOCKS_THEME_CONTACT_LINK

ARG CANVAS_BLOCKS_THEME
ENV CANVAS_BLOCKS_THEME=$CANVAS_BLOCKS_THEME

ARG CANVAS_BLOCKS_USE_CANVAS_ICONS
ENV CANVAS_BLOCKS_USE_CANVAS_ICONS=$CANVAS_BLOCKS_USE_CANVAS_ICONS

RUN yarn build-theme

FROM joseluisq/static-web-server:latest as prod
COPY --from=build /usr/src/app/dist /public
COPY ./static-web-server.toml /config.toml
ENV SERVER_CONFIG_FILE=/config.toml
EXPOSE 80