theme: jekyll-theme-cayman
title: Canvas TinyMCE Grid plugin
description: A small TinyMCE plugin to add easy to use grid functionality to Canvas's Rich Text Editor.
show_downloads: true
github:
  userscript_url: https://raw.githubusercontent.com/Ranga-Auaha-Ako/tiny-canvas-grid/master/Canvas Tinymce Patch.user.js
