theme: jekyll-theme-cayman
title: Canvas TinyMCE Grid plugin
description: A small TinyMCE plugin to add easy to use grid functionality to Canvas's Rich Text Editor.
show_downloads: true
github:
  userscript_url: https://gridbuilder.test.raa.amazon.auckland.ac.nz/canvas-grid.user.js
